language: php

sudo: true

php:
  - 7.0
  - 7.1
  - 7.2

branches:
  only: master
 
 env:  
  - LARAVEL_VERSION=5.5.*  
  - LARAVEL_VERSION=5.6.*
  
cache:
  directories:
    - $HOME/.composer/cache

services:
- sqlite


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction         - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;  
  - composer update
  
script:
- phpunit
