language: php

sudo: true

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - composer show laravel/framework
  - npm install
  - npm run dev

script:
- vendor/bin/phpunit
